#!/bin/sh
# Print the "plausible user's shelf" bookmarks fixture, dated relative to today.
#
# Used by the start-many-bookmarks and start-many-filtered scenes at the end of
# tour.tape. The default fixture (xdg/lookit/bookmarks) ships one bookmark so
# every other still is deterministic; this one exists to show BOOKMARKS carrying
# real weight.
#
# Usage, from the repo root:
#   sh docs/tui-review/fixtures/bookmarks-many.sh > path/to/bookmarks
#
# WHY THIS IS A SCRIPT AND NOT A TRACKED FILE. A pinned row's note column holds
# its last-visited date as a relative phrase ("visited 5 days ago"), so a
# hardcoded RFC 3339 stamp rots: a fixture written today saying "5 days ago"
# says "over 1 year ago" next summer, and the stills quietly stop showing what
# the scene claims. Generating the stamps at record time keeps every run
# starting from the same state, which is the whole premise of this kit.
#
# The six targets are chosen to exercise all three row shapes at once:
#   - two communities, which drop out of COMMUNITIES when pinned
#   - two service children, whose hosts then render a structural parent
#   - two targets matching no catalog entry (a user on a catalogued community
#     host, and a host lookit has never heard of)
#
# and, orthogonally, every bucket relativeDay can produce, so the note column
# can be judged at its narrowest and its widest in one frame:
#   today · yesterday · N days ago · N months ago · over 1 year ago · unknown
#
# The undated row is deliberately last, next to a dated one: a blank note has
# to read as "not visited yet" rather than as a feature that failed to render,
# and it only reads that way beside the dates it is missing.

set -eu

# stamp <days ago> -> RFC 3339 UTC at seconds precision, the one form
# parseBookmarkTarget accepts. BSD date first (macOS is the primary target),
# GNU date as the fallback so this works on a Linux clone too.
stamp() {
	date -u -v-"$1"d +%Y-%m-%dT%H:%M:%SZ 2>/dev/null ||
		date -u -d "$1 days ago" +%Y-%m-%dT%H:%M:%SZ
}

cat <<EOF
# Generated by docs/tui-review/fixtures/bookmarks-many.sh — do not hand-edit.
# The dates are relative to the recording, so the note column reads the same
# on every run.
jonathan@tilde.team $(stamp 0)
@cosmic.voyage $(stamp 1)
@plan.cat $(stamp 5)
bonsai@flanigan.us $(stamp 90)
quake@bbs.airandwave.net $(stamp 400)
someone@example.org
EOF
