package render

import (
	"strings"
	"unicode"
	"unicode/utf8"

	"github.com/charmbracelet/colorprofile"
	"github.com/charmbracelet/x/ansi"
	"github.com/jonathandeamer/lookit/finger"
)

// NoBodyLine marks a display row generated by lookit rather than originating
// in a physical response-body line.
const NoBodyLine = -1

// LayoutOptions controls the two deliberately independent wrapping paths.
// ErrorWidth is the full reader width and hard-wraps generated errors;
// BodyWidth enables whitespace-only response-body wrapping when positive.
type LayoutOptions struct {
	ErrorWidth int
	BodyWidth  int
}

// Layout is rendered response text plus the source identity of each display
// row. LineMap includes the empty row after the renderer's final newline.
type Layout struct {
	Text          string
	LineMap       []int
	BodyLineCount int
}

// LogicalLineAt returns the prepared physical body line represented by a
// display row. Indices clamp to the available display rows.
func (l Layout) LogicalLineAt(displayLine int) int {
	if len(l.LineMap) == 0 {
		return NoBodyLine
	}
	displayLine = max(0, min(displayLine, len(l.LineMap)-1))
	return l.LineMap[displayLine]
}

// DisplayLineFor returns the first display segment for a logical body line.
// Logical indices clamp to the nearest available body line.
func (l Layout) DisplayLineFor(logicalLine int) int {
	if l.BodyLineCount == 0 {
		return 0
	}
	logicalLine = max(0, min(logicalLine, l.BodyLineCount-1))
	for displayLine, mapped := range l.LineMap {
		if mapped == logicalLine {
			return displayLine
		}
	}
	return 0
}

// RenderLayout renders a response and optionally lays out each physical body
// line at word boundaries. Existing Render entry points use BodyWidth zero.
func RenderLayout(t finger.Target, body []byte, queryErr error, profile colorprofile.Profile, darkBackground bool, opts LayoutOptions) Layout {
	theme := NewThemeWithBackground(profile, darkBackground)
	var text strings.Builder
	lineMap := make([]int, 0)
	bodyLineCount := 0

	if len(body) == 0 && queryErr == nil {
		text.WriteString(theme.Footer.Render("(no response body)"))
		text.WriteByte('\n')
		lineMap = append(lineMap, NoBodyLine)
	} else if len(body) > 0 {
		if isTildeTeam(t) {
			body = reflowPronouns(body)
		}
		lines := strings.Split(string(body), "\n")
		if strings.HasSuffix(string(body), "\n") {
			lines = lines[:len(lines)-1]
		}
		bodyLineCount = len(lines)
		for logicalLine, line := range lines {
			styled := highlightFields(theme, []byte(line), extraFieldPrefixes(t))
			segments := []string{styled}
			if opts.BodyWidth > 0 {
				segments = wordWrapBodyLine(styled, opts.BodyWidth)
			}
			for _, segment := range segments {
				text.WriteString(segment)
				text.WriteByte('\n')
				lineMap = append(lineMap, logicalLine)
			}
		}
	}

	if queryErr != nil {
		errorText := queryErr.Error()
		if opts.ErrorWidth > 0 {
			errorText = ansi.Wrap(errorText, opts.ErrorWidth, "")
		}
		for _, line := range strings.Split(errorText, "\n") {
			text.WriteString(theme.ErrLine.Render(line))
			text.WriteByte('\n')
			lineMap = append(lineMap, NoBodyLine)
		}
	}

	lineMap = append(lineMap, NoBodyLine)
	return Layout{Text: text.String(), LineMap: lineMap, BodyLineCount: bodyLineCount}
}

// wordWrapBodyLine wraps one already-styled physical body line at whitespace.
// Tabs and whitespace-only lines are layout-bearing and pass through intact;
// an overlong non-whitespace token is likewise never split.
func wordWrapBodyLine(line string, width int) []string {
	if width <= 0 || strings.ContainsRune(line, '\t') ||
		strings.TrimSpace(line) == "" || ansi.StringWidth(line) <= width {
		return []string{line}
	}

	var lines []string
	var current, word, space strings.Builder
	currentWidth, wordWidth, spaceWidth := 0, 0, 0
	state := byte(ansi.NormalState)
	parser := ansi.NewParser()

	flushLine := func() {
		lines = append(lines, current.String())
		current.Reset()
		currentWidth = 0
	}
	placeWord := func() {
		if word.Len() == 0 {
			return
		}
		if currentWidth > 0 && currentWidth+spaceWidth+wordWidth > width {
			flushLine()
			space.Reset()
			spaceWidth = 0
		}
		current.WriteString(space.String())
		current.WriteString(word.String())
		currentWidth += spaceWidth + wordWidth
		space.Reset()
		word.Reset()
		spaceWidth, wordWidth = 0, 0
	}

	for rest := line; rest != ""; {
		seq, cellWidth, n, nextState := ansi.DecodeSequence(rest, state, parser)
		state, rest = nextState, rest[n:]
		plain := ansi.Strip(seq)
		r, _ := utf8.DecodeRuneInString(plain)
		if plain != "" && unicode.IsSpace(r) && r != '\u00a0' {
			placeWord()
			space.WriteString(seq)
			spaceWidth += cellWidth
			continue
		}
		word.WriteString(seq)
		wordWidth += cellWidth
	}
	placeWord()
	current.WriteString(space.String())
	if current.Len() > 0 || len(lines) == 0 {
		lines = append(lines, current.String())
	}
	return lines
}
